= Taack JDBC Pilote
:doctype: book
:taack-category: 0|more/JDBC
:toc:
:source-highlighter: rouge

== Qu'est-ce que c'est ?

JDBC signifie *Java Database Connectivity*. C'est un composant Java ancien, important et très utilisé. Il simplifie l'interrogation et l'édition des données entre différents Programmemes.

Notre implémentation JDBC actuelle permet uniquement d'interroger les données depuis l'intranet.

La mise à jour des données par ce biais est un sujet complexe. Nous devons gérer les droits des utilisateurs et la validation des données qui ne sont pas décrits au niveau de la base de données, mais directement dans le code de l'intranet. Une nouvelle approche est nécessaire de notre côté pour éviter de dupliquer le code.

C'est en cours.

.Diagramme de séquence lors de l'exécution d'une requête sans erreur
[plantuml,format="svg",opts="online"]
----
@startuml
group Querying Object using TQL
        Vous -> Programme : Type the Query
        activate Programme
        Programme -> Pilote : Transmission de la requête
        Pilote -> Intranet : Transmission de la requête
        Intranet -> Intranet : Validation Grammaire TQL
        Intranet -> Intranet : Validation Tables et champs
        Intranet -> Intranet : Traduction TQL à HQL
        Intranet -> Intranet : Traduction HQL à SQL
        note right
            Le **SQL** est le langage
            natif de la base de données
        end note
        Intranet -> Database : Transmission du SQL
        activate Database #000055
        Database -> Intranet : Réception des résultats
        deactivate Database
        Intranet -> Intranet : Empaquetage des résultats
        Intranet -> Pilote : Transmission des résultats
        Pilote -> Pilote : Dépacketage
        Pilote -> Programme : Transmission des résultats
        Programme -> Vous : Montrer les résultats
        deactivate Programme
        Vous -> Programme : Vous faire défiler \nles résultats
        note right
            **Programme** demandera
            de nouvelle données,
            en utilisant un **offset**
        end note
end

box "Vousr Computer" #LightBlue
    participant Programme
    participant Pilote
end box
box "The Intranet Server" #Yellow
    participant Intranet
    participant Database
end box

@enduml
----

== Où interroger les données avec ce pilote ?

Seuls *3 logiciels* ont été testés avec ce pilote jusqu'à présent :
|===
|Programmeme |Introspection ?|Interrogation ? |Mise à jour ? | Insertion ?

|LibreOffice 7.3 |Liste de tables uniquement|Oui |Non | Non
|dBeaver |Oui |Oui |Pas encore | Pas encore
|Intellij |Oui |Oui |Pas encore | Pas encore
|===

#Introspection# vous aide lors de l'écriture de requêtes avec la *complétion automatique*. Lors de la saisie de la requête, le Programmeme vous indiquera les tables et champs disponibles.

Il existe 2 modèles de travail pour analyser les données :

* Écrire et tester la requête dans un logiciel supportant *Introspection* ;
* Ensuite, soit :
** Utiliser la requête saisie directement dans *LibreOffice*
** Ou travailler avec une *extraction CSV* et la mettre dans n'importe quel logiciel (y compris *Office*)

ATTENTION : je ferai des vidéos plus tard sur la façon de configurer le pilote avec ces Programmemes.

== Requêtes TQL

La principale différence avec un pilote JDBC classique et le nôtre est le langage de requête.

Nous avons développé le *TQL* (Taack Query Language), voici quelques avantages :

* Sécurisé, on vérifie la requête typée avant de l'envoyer à la vraie base de données
* Syntaxe facile :
** Moins besoin de jointures
** Accès aux champs référencés (voir <<easy-syntax>> point (2))
* Agnostique à la base de données

=== Structure des requêtes de base

[source,sql]
[[easy-syntax]]
.TQL Basic Sample
----
select <1>
    l.client.firstName, <2>
    l.rep.username <2>
from Lead l <3>
where l.dateCreated > '2022-01-01' <4>
----
<1> #Clause Select#, permettant de sélectionner des *colonnes* ;
<2> #Champs déférés#, si la colonne est elle-même un objet, vous pouvez accéder de manière récursive aux champs de l'objet. Ici rep est un objet `User` qui contient des champs en lui-même (comme `username`);
<3> #Clause From#, permettant de choisir des *tables*, ici on utilise un _alias_ `l`
<4> #Clause Where# permettant de filtrer les données.

=== Requêtes de base avec des formules

Il est possible d'ajouter des formules arithmétiques dans la clause select.

[source,sql]
[[basic-query-with-formulas]]
.Exemple de base TQL avec formules
----
select
    ll.lead.name,
    ll.qty * ll.salePrice as totalWoTaxes <1>
from LeadLine ll
where ll.qty * ll.salePrice > 100 <2>
----
<1> #Clause Select#, prend en charge à la fois les `alias de colonne` et les opérations arithmétiques
<2> #Clause Where# prend également en charge l'arithmétique

AVERTISSEMENT : le nom d'alias de colonne doit commencer par une lettre minuscule et faire uniquement partie du jeu de caractères ASCII7.

.Résultats Exemple de base avec formules
|===
|lead.name |totalWoTaxes

|Balisage pylône SFR site 240087 (Hivory)
|250.00000000

|Balisage pylône SFR site 240087 (Hivory)
|340.00000000

|Balisage pylône SFR site 240087 (Hivory)
|3410.00000000

|Système AWL IR à faible intensité EL BJORN
|2700.00000000
|===

=== Requêtes avec regroupement

La clause de regroupement ajoute la capacité d'agréger les données. La <<requête de base avec formules>> n'est pas utile, car il y a une ligne par ligne d'offre. Il est possible d'utiliser le regroupement afin d'obtenir une ligne par offre, comme dans l'exemple suivant :

[source