= Sources
:doctype: book
:taack-category: 2|more/resources
:source-highlighter: rouge

== Github

=== This website content

https://github.com/Taack/taack-website-content

We use asciidoc format to write documentations, for localization, we suffix the file name with the language. Default language is English. `WhyDSL-fr.doc` will be the French version, `WhyDSL.adoc` the english one (default one).

=== Intellij Autocomplete sources

https://github.com/Taack/taack-autocomplete

We will release Intellij plugin binaries in this repo, for each Intellij releases.

=== Infra Sources

https://github.com/Taack/infra

Infra contains 3 subprojects (`taack-jdbc-common` being shared):

* `client` set of kotlin files transpiled into Javascript. This project avoid writing complex Javascript, assembly of this project is directly copied in `taack-ui` assets.
* `taack-jdbc-client` source of the JDBC Driver
* `taack-ui` Grails plugin sources


=== Intranet Sample App

https://github.com/Taack/intranet

This app can be use as a skeleton for your future developments.
