= Reference Doc.
:doctype: book
:taack-category: 10|doc/DSLs
:toc:
:source-highlighter: rouge

== BlockSpec

=== Width
Width ratio of the block.

Possible values:

* MAX
* THREE_QUARTER
* TWO_THIRD
* HALF
* THIRD
* QUARTER


=== blockTabs

Embeds one or multiple tabs
----
blockTabs(BlockSpec.Width, <1>
          Closure)         <2>
----
<1> <<Width>> value
<2> Closure should only contain link:blocktab[blockTab] children

=== blockTab

Describe the content of a tab. must be children of <<blockTabs>>

----
blockTab(String,        <1>
         Closure)       <2>
----
<1> Tab title
<2> Closure containing tab content

=== modal

Pop a modal. Nested blocks will be displayed inside this modal.
----
modal(boolean,          <1>
      Closure)          <2>
----
<1> If true create a new modal, if false, replace the content of the top modal (_Optional; Default value: True_)
<2> Closure content of the modal

=== form
Add a form to a block.
----
form(String,            <1>
     UiFormSpecifier,   <2>
     Width,             <3>
     Closure)           <4>
----
<1> Title that will appear in form header
<2> The form descriptor. See <<UiFormSpecifier>>
<3> The form block <<Width>> (_Optional; Default value: MAX_)
<4> Closure containing the actions that will appear in the form header. See <<BlockActionSpec>>

=== show
Add a "show" to a block. A "show" is used to display object data with limited edition capabilities

----
show(String,            <1>
     UiShowSpecifier,   <2>
     Width,             <3>
     Closure)           <4>
----
<1> Title that will appear in the show header
<2> The show descriptor. See <<UiShowSpecifier>>
<3> The show block <<Width>>
<4> Closure containing the actions that will appear in the show header. See <<BlockActionSpec>>

=== table
Add a table without filtering capabilities to a block. To use a table with a filter, see <<tableFilter>>.

----
table(String,           <1>
      UiTableSpecifier, <2>
      Width,            <3>
      Closure)          <4>
----

<1> Title that will appear in the table header (_Optional_)
<2> The table descriptor. See <<UiTableSpecifier>>
<3> The table block <<Width>> (_Optional; Default value: MAX_)
<4> Closure containing the actions that will appear in the table header. See <<BlockActionSpec>>

=== tableFilter
Add a table and its associated filter to a block

----
tableFilter(String,             <1>
            UiFilterSpecifier,  <2>
            String,             <3>
            UiTableSpecifier,   <4>
            Width,              <5>
            Closure)            <6>
----

<1> Title that will appear in the filter header
<2> The filter descriptor. See <<UiFilterSpecifier>>
<3> Title that will appear in the table header
<4> The table descriptor. See <<UiTableSpecifier>>
<5> The Width of the block containing the filter and table. (_Optional; Default value: MAX_)
<6> Closure containing the actions that will appear in the table header. See <<BlockActionSpec>>

=== chart
Add a chart to a block

----
chart(String,           <1>
      UiChartSpecifier, <2>
      Width,            <3>
      Closure)          <4>
----
<1> Title that will appear in the chart header
<2> The chart descriptor. See <<UiChartSpecifier>>
<3> The chart block <<Width>> (_Optional; Default value: MAX_)
<4> Closure containing the actions that will appear in the chart header

=== custom
Add a block containing custom HTML code

----
custom(String,          <1>
       String,          <2>
       Style,           <3>
       Width,           <4>
       Closure)         <5>
----
<1> The custom block title (_Optional_)
<2> The html code that will be rendered in the block
<3> The template style to use. See <<Style>> (_Optional_)
<4> The custom block <<Width>> (_Optional; Default value: MAX_)
<5> Closure containing actions that will appear in the header of the block (_Optional_)

== BlockActionSpec
Class allowing to list actions in tables, shows, filterTables and charts header

=== action
Display an action icon

----
action(String,          <1>
       ActionIcon,      <2>
       MethodClosure,   <3>
       Long/Map,        <4>
       boolean)         <5>
----
<1> Hover text
<2> <<ActionIcon>> to display
<3> Target action when button is clicked
<4> *Long* ID OR Parameters *Map*
<5> Set to true if target action is ajax

== ActionIcon
ActionIcons helps you put and style icons in your app more easily.
The benefits of using objects is that you can use operators with the ActionIcon.

For example, if we want to have an icon that is scaled down we can multiply an ActionIcon by the <<ActionIconStyleModifier>> value "SCALE_DOWN" like so
----
ActionIcon.CREATE * ActionIconStyleModifier.SCALE_DOWN
----

Taack-UI also ships with many ActionIcons integrated, but you can also create your own ActionIcon object with the asset you want.
----
ActionIcon Book = new ActionIcon("/assets/icons/book.svg")
----

.List of ActionIcon available in Taack-UI
[%collapsible]
====
* CREATE
* EDIT
* SAVE
* DOWN
* SHOW
* UP
* DELETE
* IMPORT
* EXPORT
* EXPORT_PDF
* EXPORT_CSV
* DOWNLOAD
* ADD
* SELECT
* UNSELECT
* FILTER
* DETAILS
* CONFIG
* CONFIG_USER
* SEARCH
* REFRESH
* MERGE
* REPLY
* COPY
* MAIL
* HELP
* GRAPH
* GANTT
* TIMING
* START
* STOP
* OPERATOR_NOT
* OPERATOR_PLUS
* OBJECT_CUSTOMER
* OBJECT_PRODUCT
* OBJECT_RANGE
* OBJECT_FLAG
====

=== ActionIconStyleModifier
Helps you add style modifier to ActionIcons

Enum value available:

* SCALE_DOWN
* RIGHT
* LEFT

== Style
The Style class helps you style ActionIcons, Blocks, etc.
----
Style style = new Style(String,         <1>
                        String,         <2>
                        boolean,        <3>
                        boolean)        <4>
----
<1> The css classes that will be applied
<2> The inline css that will be applied
<3> If the styled object should be a div
<4> If the style should apply to label

Taack-UI also ships with basic Styles by default.

.Complete list of default Styles
[%collapsible]
====
* RED
* BLUE
* GREEN
* ORANGE
* YELLOW
* BOLD
* ITALIC
* EMPHASIS
* SMALLER
* DISABLED
* ENABLED
* BREAK_AFTER
* NO_BREAK_AFTER
* NO_BORDER
* TAG
* BLUE_TAG
* GREEN_TAG
* YELLOW_TAG
* ORANGE_TAG
* RED_TAG
* GREY_TAG
* WHITE_TAG
* ALIGN_RIGHT
* ALIGN_CENTER
* NOWRAP
* LABEL_WIDTH90PX
* LABEL_WIDTH120PX
* LABEL_WIDTH150PX
* LABEL_MARGIN_TOP5PX
* LABEL_MARGIN_BOTTOM5PX
* MARKDOWN_BODY
====