= Modular Directory Layout
:doctype: book
:taack-category: 5|doc/Concepts
:toc:
:source-highlighter: rouge

= Modular Application Development

The https://github.com/Taack/intranet[Intranet Sample App] is a modular https://gradle.org/[Gradle] application. You can get instructions to run it clicking on: link:../../usage.adoc[Install Sample Intranet].

== Intranet Sample App Directory Layout


[plantuml, format="svg", opts="inline", theme="spacelab"]
----
@startsalt
{
{T
+ <&folder> Intranet | Root Directory
++ <&folder> app    | Application Modules Directory
+++ <&folder> crew  | Mandatory base app to manage users
+++ <&folder> appModule1  | First application (Gradle module)
+++ <&folder> appModule2  | Second application
+++ <&folder> ...   | And so on
++ <&folder> buildSrc | Gradle Build Instructions
++ <&folder> server | Server Root Application (Grails app)
++ <&folder> gradle           | Gradle binaries
++ <&file> build.gradle
++ <&file> settings.gradle
++ <&file> gradle.properties
++ <&file> gradlew
}
}
@endsalt
----

=== _app_ directory

Hold Grails plugins (or Gradle modules) that compose the Intranet application. Those plugins should have minimal dependencies to maximize reusability by others.

==== _crew_ directory

Part of the application responsible for user management, only mandatory app that currently holds the Taack services.

=== _server_ directory

Grails application holding global configuration, common translations, static shared assets, and the root page.

The *server* grails application depends on all application modules (or Grails plugins) defined in the app directory that are desired.

=== _buildSrc_

Common Gradle configuration. Additional Gradle tasks might be defined into this directory using Groovy language.

== _infra_ repository

Holds the sources of the *taack-ui* plugin.

[plantuml, format="svg", opts="inline"]
----
@startsalt
{
{T
+ <&folder> infra     | Infra sources (see below)
++ <&folder> browser   | Browser code (Kotlin transpiled in Javascript)
++ <&folder> taack-jdbc-common| Common JDBC code
++ <&folder> taack-jdbc-client| Client JDBC code
++ <&folder> taack-ui | Taack User Interface code
++ <&folder> gradle           | Gradle binaries
++ <&file> build.gradle
++ <&file> settings.gradle
++ <&file> gradle.properties
++ <&file> gradlew

}
}
@endsalt
----

* the _browser_ folder contains code that will be executed into the browser
* _taack-jdbc-common_ common classes shared between _taack-ui_ and _taack-jdbc-client_
* _taack-jdbc-client_ the JDBC driver (see link:../../more/JDBC/taack-jdbc-driver.adoc[taack-jdbc-driver])
