= 具体应用
:taack-category: 2|doc/UserGuide
:toc:
:source-highlighter: rouge
:icons: font

这些具体应用场景将展示开发人员在开发过程中的职责 (对应到图表中就是控制器参与者)，以及框架在开发过程中的作用 (对应到图表中就是蓝色长方形部分)。

== 显示表单，保存数据对象

这个过程有2个Action参与，并涉及使用了2个Service：

.表单流程时序图
[plantuml,format="svg",opts={optsi}]
----
@startuml
group Display Form
    user -> controller : click on create or edit
    activate controller
    controller -> controller : buildForm
    controller -> controller : buildBlock
    controller -> taackUiService : show(block)
    deactivate controller
    activate taackUiService #005500
    note right
        choose Ajax or
        full page rendering
        to render the block
    end note
    taackUiService -> user : show the block containing the form
    deactivate taackUiService
end

box "Taack Service" #LightBlue
    participant taackUiService
    participant taackSaveService
end box

== Edit Form ==

group Save Form
    user -> controller : click save
    activate controller
    controller -> taackSaveService : saveThenRedirectOrRenderErrors
    deactivate controller
    activate taackSaveService
    taackSaveService -> taackSaveService : save
    taackSaveService -> taackSaveService : redirectOrRenderErrors
    alt valid object
        taackSaveService -> user : redirect to target action
    else invalid object
        taackSaveService -> user : ajax form rendered with errors
        deactivate taackSaveService
    end
end
@enduml
----

.代码示例：表单+保存流程
[,groovy]
----
def userForm(User user) {                           <1>
    user ?= new User()                              <2>

    UiFormSpecifier f = new UiFormSpecifier()       <3>
    f.ui user, {
        hiddenField user.subsidiary_
        hiddenField user.origin_
        section "User", {
            field user.username_
            field user.firstName_
            field user.lastName_
            ajaxField user.manager_, this.&selectUserM2O as MC
            field user.trigram_
            field user.password_
        }
        section "Coords", {
            field user.businessUnit_
            field user.job_
            field user.directPhone_
            field user.additionalPhone_
            field user.mail_
            field user.mainSubsidiary_
            field user.allowedSubsidiaries_
        }
        // [. . .]
        formAction this.&saveUser as MC, user.id    <4>
    }

    taackUiService.show new UiBlockSpecifier().ui { <5>
        modal {
            form "User Form", f, BlockSpec.Width.MAX
        }
    }
}

@Transactional
@Secured("ROLE_ADMIN")                              <6>
def saveUser() {                                    <7>
    taackSaveService.saveThenRedirectOrRenderErrors(User, this.&listUser) <8>
}
----

<1> 负责显示表单的Action
<2> 若数据对象不存在，则新建
<3> 创建表单块
<4> 表单提交按钮，负责传输表单数据至 `saveUser` Action中
<5> 将表单呈现在页面上
<6> 给该Action添加权限管理
<7> 负责保存数据对象的Action
<8> 调用taackSaveService，若验证通过，则将页面重定向至 `listUsers` 。

== 显示表格，附带可排序列、行内按钮、以及筛选器

只需要一个Action即可管理翻页、筛选、以及排序：

.表格管理流程时序图
[plantuml,format="svg",opts={optsi}]
----
@startuml
group Display Table with filter
    loop as much as the user click on the table
        user -> controller : filter or sort objects
        activate controller
        controller -> controller : buildFilter (optionaly)
        controller -> controller : buildTableHeader
        controller -> taackFilterService : iterate
        activate taackFilterService #005500
        controller -> controller : build row from object
        return loop over each row
        controller -> controller : buildBlock
        controller -> taackUiService : show(block)
        deactivate controller
        activate taackUiService #005500
        note right
            choose Ajax or
            full page rendering
        end note
        taackUiService -> user : show the table and the filter if any into the block
        deactivate taackUiService
    end
end

box "Taack Service" #LightBlue
    participant taackUiService
    participant taackFilterService
end box

@enduml
----

.代码示例：筛选器与表格
[,groovy]
----
def index() {                                                   <1>
    User cu = authenticatedUser as User

    UiFilterSpecifier f = buildUserTableFilter cu               <2>
    UiTableSpecifier t = buildUserTable f                       <3>

    UiBlockSpecifier b = new UiBlockSpecifier().ui {            <4>
        tableFilter(f, t) {
            menuIcon ActionIcon.ADD, this.&userForm as MC       <5>
        }
    }

    taackUiService.show(b, buildMenu())                         <6>
}
----

<1> 负责列出数据的Action
<2> 构建筛选器。这里它以当前用户作为参数，因为该表格想要列出当前用户所在的团队的所有人员。
<3> 构建表格
<4> 构建总块以包含进筛选器块与表格块
<5> 添加按钮，负责创建新用户
<6> 将该块呈现在页面上

WARNING: 我们特意将构建好的筛选器传入buildTable中，是为了进行数据查询以及预防**黑客**


== 显示弹窗、关闭弹窗、更新页面一部分内容

.弹窗管理流程时序图
[plantuml,format="svg",opts={optsi}]
----
@startuml
group Open Modal, Edit or create object, then refresh the page
    user -> controller : click on create or edit
    activate controller
    controller -> controller : buildForm
    controller -> controller : buildBlock
    controller -> taackUiService : show(block)
    deactivate controller
    activate taackUiService #005500
    note right
        The block open a modal
    end note
    taackUiService -> user : show the block containing the form
    deactivate taackUiService
end

box "Taack Service" #LightBlue
    participant taackUiService
    participant taackSaveService
end box

== Edit Form ==

group Save Form
    user -> controller : click save
    activate controller
    controller -> controller : buildBlock
    note left
        Here, the block contains
        **closeModalAndUpdateBlock**
    end note
    controller -> taackSaveService : saveThenDisplayBlockOrRenderErrors
    deactivate controller
    activate taackSaveService
    taackSaveService -> taackSaveService : save
    taackSaveService -> taackSaveService : displayBlockOrRenderErrors
    alt valid object
        taackSaveService -> user : close modal and refresh current page
    else invalid object
        taackSaveService -> user : ajax form rendered with errors
        deactivate taackSaveService
    end
end
@enduml
----

.代码示例：关闭弹窗与刷新页面内容
[,groovy]
----
taackSaveService.saveThenDisplayBlockOrRenderErrors(EngineeringChangeRequest,   <1>
new UiBlockSpecifier().ui {                                                     <2>
    closeModalAndUpdateBlock {                                                  <3>
        show "Projects", buildShowProjects(ecr), BlockSpec.Width.MAX, {
            action
                ActionIcon.ADD,
                Ecr2Controller.&projectsForm as MC,
                [id: ecr.id, ajaxBlockId: ajaxBlockId]
        }
    }
})
----

<1> 在保存数据对象之后调用新一轮弹窗，其内您可以选择关闭弹窗并刷新页面内容，所有步骤都在同一个Action内完成。
<2> `saveThenDisplayBlockOrRenderErrors` 采用 `UiBlockSpecifier` 作为参数
<3> `closeModalAndUpdateBlock` 将会关闭弹窗并应用新内容至当前页面


== 待做事项

* Updating a portion of a page

* Show some object with an editable field

* Show a graph

* Export a table in CSV

* Rendering a block in a PDF

* Rendering a block in a Mail

* ...
