= Installation
:doctype: book

== Prérequis

Pour commencer, vous aurez besoin des éléments suivants :

* Java (JDK-17)
* git

En option, vous pouvez aussi installer :

* Solr-9.1.0 (Utilisé pour la barre de recherche côté Intranet)
* Postgresql (Si vous n'avez aucun gestionnaire de base de données, vous devrez utiliser la base de données en mémoire de Grails)

== Clonez le projet Intranet clé en main

[,bash]
----
git clone https://github.com/Taack/intranet.git
----

Ce dépôt contient une version simplifiée d'un Intranet dans lequel vous pourrez ajouter d'autres applications. Il contient "Crew", qui est le système de gestion des utilisateurs, ainsi que sa dépendance de sécurité : Spring Security Plugin.

== Lancez le projet Intranet

Allez dans le répertoire intranet nouvellement cloné et démarrez le serveur en exécutant cette commande :

[,bash]
----
./gradlew server:bootRun
----

Après un certains temps, vous devriez voir dans la console le message suivant :

____
Grails application running at http://localhost:9442...
____

Vous pouvez maintenant accéder à l'Intranet en allant à cette adresse depuis votre navigateur. Vous pouvez aussi vous identifier avec les identifiants par défaut (identifiant : admin, mot de passe : ChangeIt). Le mot de passe peut être remplacé dans le fichier server/grails-app/conf/application.yml.

== Configurez votre IDE

Nous recommandons fortement d'utiliser la dernière version d'IntelliJ Ultimate Edition, pour son support étendu de Groovy et Grails. Nous étudions actuellement le support d'autres IDE (Eclipse, Visual Studio Code), ainsi que le support des autres versions d'IntelliJ.

=== IntelliJ Ultimate Edition

Nous vous recommendons d'installer les plugins Taack pour IntelliJ que vous pouvez trouver https://github.com/Taack/infra/releases/tag/v0.1[ici].

Pour ouvrir le projet, sélectionnez "Open projet" et sélectionnez `intranet/server/settings.gradle`.

=== Visual Studio Code

Si vous voulez vraiment utiliser Visual Studio Code, nous vous recommandons les extensions suivantes pour utiliser ce framework :

* https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack[Extension Pack for Java]
* https://marketplace.visualstudio.com/items?itemName=marlon407.code-groovy[code-groovy]
* https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle[Gradle for Java]
* https://marketplace.visualstudio.com/items?itemName=MellowMarshmallow.groovy[Groovy]

Gardez à l'esprit que la plupart des fonctionnalités de Grails et de Taack Framework ne seront pas reconnues par VSCode mais celui-ci peut toujours être utilisé. De plus, VSCode ne vous proposera pas d'aide avec les importations, la navigation dans le code ainsi que de nombreuses autres fonctionnalités pratiques puisque le support de Groovy n'est pas aussi avancé que sur IntelliJ.
