= Installation
:doctype: book
:taack-category: 1
:toc:

== Requirements

First of all, you will need the following:

* Java (JDK-17)
* git

You can also optionally install:

* Solr-9.1.0 (Used for intranet-wide search bar)
* Postgresql (You will need to use the Grails in-memory database if you don't have any database manager)

== Cloning the ready-to-dev Intranet

[,bash]
----
git clone https://github.com/Taack/intranet.git
----

This repository includes a stripped-down version of an intranet on top of which you can build more applications. It includes "Crew", the user management system and it's security dependency: Spring Security Plugin.

== Start your intranet

Navigate inside the newly cloned intranet folder and start the server by executing this command:

[,bash]
----
./gradlew server:bootRun
----

After a while you should see in the console:

____
Grails application running at http://localhost:9442...
____

You can now access the intranet by going to that address in your browser. You can also login with the default credentials (username: admin; password: ChangeIt). The password can be changed in server/grails-app/conf/application.yml.

== Set up your IDE

We heavily recommend the latest IntelliJ Ultimate Edition for its extensive Groovy and Grails support. We are investigating other IDE support (Eclipse, Visual Studio Code), and also support for IntelliJ non Ultimate Edition.

=== IntelliJ Ultimate Edition

We recommend installing the IntelliJ Taack Plugins that you can find https://github.com/Taack/infra/releases/tag/v0.1[here].

To open the project, select "Open project" and select `intranet/server/settings.gradle`.

=== Visual Studio Code

If you really want to use Visual Studio Code, we recommend the following extensions to use this framework:

* https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack[Extension Pack for Java]
* https://marketplace.visualstudio.com/items?itemName=marlon407.code-groovy[code-groovy]
* https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle[Gradle for Java]
* https://marketplace.visualstudio.com/items?itemName=MellowMarshmallow.groovy[Groovy]

Keep in mind that most of the Grails and Taack Framework features will not be recognized by VSCode but are still usable. In addition, VSCode will not help you with imports, code navigation, and many QoL features will be unavailable since groovy support is not as extensive as IntelliJ.
